### ISSUE TITLE
Damage from looking at Wood

### ISSUE THREAD

**Issue by TheUntamed** [oitsjustjose/Natural-Progression#86] opened 2024-05-21 09:04 UTC
Version: 2.3.6 for MC 1.20.1

Taking damage when hitting wood with the bare hand works fine, but I also take damage just from looking at it. This includes tree logs as well as stripped wood and planks (which makes sense, those shouldn't be obtainable by hand either.)

Another thing is the message that shows up as soon as you look at wood. Maybe that's connected to the issue above and should only show if you try to break the wood. Because currently its shown all the time I look at my wooden floor or wall.

Edit: Same problem for other blocks like stone as well.

**Comment by oitsjustjose** [comment] 2024-05-22 14:41
Duplicate of #84 - I'm unsure how to fix this at the moment and haven't had too much time to investigate.

**Closed as completed by oitsjustjose** 2024-05-22 14:41 UTC
