### ISSUE TITLE
Create Pebbles Appearing Without Textures.

### ISSUE THREAD

**Issue by Cheesedoghotdog** [oitsjustjose/Natural-Progression#81] opened 2023-12-03 22:43 UTC
Hey, just tried adding Create to this mod and the various pebbles based on Create stones are showing up as missing textures. Is there any way to disable these pebbles? This is on the Forge 1.20.1 version of both mods.

**Comment by oitsjustjose** [comment] 2023-12-14 13:19
Duplicate of https://github.com/oitsjustjose/Natural-Progression/issues/76 - working on this now.

**Closed as completed by oitsjustjose** 2023-12-14 13:19 UTC
